# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS-10.13'

steps:
- script: git submodule update --init --recursive
  displayName: Update git submodules
- script: bundle update --bundler
  displayName: Update bundler
- script: rake setup
  displayName: 'configure the project'
