app_name: Posts
workspace_path: Posts.xcworkspace
project_path: Posts.xcodeproj

setup:
  bundler:
    enabled: true
    path: # optional, primarly taken from ENV['BUNDLER_PATH'] then here
  brew:
    enabled: false
    formulas:
      - git
  submodules:
    enabled: true
  cocoapods:
    enabled: true
  carthage:
    enabled: false

swiftgen:
  strings:
    enabled: false
    path: Pods/SwiftGen/bin/swiftgen
    template: dot-syntax-swift3
    strings:
      'Watch Extension/Resources/en.lproj/Localizable.strings': 'Watch Extension/Generated/L10n.swift'

xcode:
  version: 10.1*
  build_path: build # primarly taken from ENV['ARTIFACTS_PATH'] then here
  reports_path: reports # primarly taken from ENV['TEST_REPORTS_PATH'] then here
  tests:
    scheme: Posts
    destinations:
      - 'platform=iOS Simulator,OS=12.1,name=iPhone X'
  release:
    prod:
      scheme: Posts
      configuration: Release
      output: Posts
